move instascale source to project
project-codeflare/instascale pull request #1
Opened 2022-12-13 20:46 UTC by asm582

2022-12-13 23:18 UTC, Maxusmusti requested changes
Looks good, just need to make sure to adjust any old IBM references

2022-12-13 23:18 UTC, Maxusmusti commented on go.mod
> +module github.ibm.com/asmalvan/instascale-1
Needs to be adjusted for new home

2022-12-13 23:18 UTC, Maxusmusti commented on go.mod
> +	github.com/IBM/multi-cluster-app-dispatcher v0.0.0-20220426132040-4cb2f1b93df4
Same here

2022-12-14 01:54 UTC, asm582 commented on go.mod
> +module github.ibm.com/asmalvan/instascale-1
Done, Thanks

2022-12-14 01:54 UTC, asm582 commented on go.mod
> +	github.com/IBM/multi-cluster-app-dispatcher v0.0.0-20220426132040-4cb2f1b93df4
Done, Thanks

2022-12-14 18:05 UTC, Maxusmusti approved these changes

2022-12-14 18:12 UTC, merged